config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :except => [:index]
  resources :groups
  resources :memberships
  resources :tournaments do
    resources :matches
  end

  get 'head_to_head/:id', to: 'groups#ajax_head_to_head'

  root to: 'users#show'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :tournaments

  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def create
    group = Group.new(group_params)
    if (group.save)
      #need to also create your own membership
      Membership.create(user_id: current_user.id, group_id: group.id, status: "active")
      redirect_to user_path(current_user.id)
    else
      flash[:alert] = "Group name cannot be blank"
      redirect_to user_path(current_user.id)
    end
  end

  #For showing a specific group page.
  def show
    @group = Group.find(params[:id])

    #Get the tournaments for that group
    tournaments = GetGroupTournaments.run(@group)
    @complete_tournaments = tournaments[:complete_tournaments]
    @incomplete_tournaments = tournaments[:incomplete_tournaments]
    @champs = tournaments[:champs]
    
    #Get stats for that group
    stats = GetGroupStats.run(@group)
    @group_users = stats[:group_users]
    @all_user_wins = stats[:all_user_wins]
    @all_user_losses = stats[:all_user_losses]
    @all_user_win_loss_ratios = stats[:all_user_win_loss_ratios]
    @all_user_tournament_wins = stats[:all_user_tournament_wins]

    #Render admin and user views separately
    if (current_user.id == @group.admin_id)
      render 'showGroupToAdmin'
    else
      render 'showGroupToUser'
    end
  end

  #Populating the head to head table stats if the data has been sent
  def ajax_head_to_head
    if (params[:id])
      info = params[:id].split(',')
      group_id = info[0]
      username1 = info[1]
      username2 = info[2]

      stats = GetHeadToHeadStats.run(group_id, username1, username2)
      @meetings = stats[:meetings]
      @victories = stats[:victories]
      @defeats = stats[:defeats]
    end
  end

  def destroy
    group = Group.find(params[:id])
    #Find all memberships in that group and delete it
    memberships = Membership.where("group_id = ?", group.id)
    memberships.each do |m|
      Membership.destroy(m.id)
    end
    Group.destroy(group.id)
  end


  def group_params
    params.require(:group).permit(:name, :admin_id)
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/ajax_head_to_head.js.erb
//Populate the head to head table with the appropriate values
//As designated in the AJAX request to groups#ajax_head_to_head

$(document).ready(function() { 

    $('.meetings').text(<%=@meetings%>);

    $('.victories').html(<%=@victories%>);

    $('.defeats').text(<%=@defeats%>);

    $('.head-to-head').show();
}); 

app/views/groups/showGroupToAdmin.html.erb
<%= stylesheet_link_tag :application, :media => "all" %>
<%= stylesheet_link_tag "groupPageAdmin" %>

<h1><%= @group.name %> </h1>
<div class="spacer large-1 columns">&nbsp</div>
	<section class="large-3 columns admin-view panel content">
		<% if flash[:alert] %>
			<p class="error"> <%=flash[:alert]%></p>
		<%end%>
	<!-- Creating a new tournament -->
		<h2>Admin Console </h2>
		<h3>Start a new tournament for this group</h3>
		<%= form_tag tournaments_path, method: :POST do %>
			<label>Tournament Name </label>
			<input name="tournament[name]" type="text" value="" />
			<label>What game are you playing?</label>
			<input name="tournament[game_type]" type="text" value="" />
			<label>What type of tournament?</label>
				Single Elimination 
				<input class="tournament-type" type="radio" name="tournament[double_elim]" value=<%=false%>>
				Double Elimination 
				<input class="tournament-type" type="radio" name="tournament[double_elim]" value=<%=true%>>
			<label><h5>Participants</h5></label>
			<label><p>Currently supported sizes are 4 and 8. Selections not matching this will have byes added appropriately. </p></label>
			<label class="player-counter"> Players selected: 0</label>
			<%@group.users.each_with_index do |user,i| %>
				<label class="checkbox">
					<input class ="check" type="checkbox" name="players[]" value=<%=user.username%>>
					<%=user.username%>
				</label>
			<% end %>
			<input name="tournament[group_id]" type="hidden" value=<%=@group.id%> />
			<button type="submit">Start</button>
		<% end %>
		<!--Inviting other users to your group  -->
		<label>Is someone missing? Invite a user to your group </label>
			<input class="user-to-invite" type="text" placeholder="username">
			<input class="group-id" type="hidden" value=<%=@group.id%> >
			<!-- sends ajax request -->
			<button class="invite-user"> Invite</button>
	</section>
	<div class="spacer large-1 columns">&nbsp</div>

	<section class="large-3 columns tournament-listing content">
		<!-- Link to in progress tournaments -->
		<h3>Active Tournaments</h3>
		<% if @incomplete_tournaments.empty?%>
			<p>None</p>
		<%else%>
			<% @incomplete_tournaments.each do |t| %>
				<ul>
					<li class="tournament-li"><h5> <%= link_to t.name, tournament_path(t.id) , method: :GET %></h5> </li>
				</ul>
			<% end %>
		<%end%>

		<!-- Display old tournaments and their victors -->
		<h3>Completed Tournaments</h3>
		<% if @complete_tournaments.empty? %>
			<p>None</p>
		<% else %>
			<% @complete_tournaments.each_with_index do |t,i| %>
				<ul class="completed-tournament-list"> 
					<li class="tournament-li"> <h5><%= t.name %></h5> <h5> Victor : <%=@champs[i].username%></h5> <h5><%= t.game_type%></h5> <h5>Completed on: <%=t.updated_at.to_s.split(' ')[0]%> </h5>
					<button class="delete-tournament" value=<%=t.id%>>delete</button>
					</li>
				</ul>
			<% end %>
		<% end %>
	</section>

	<!--       Stats section         -->
	<section class="large-3 columns stats content">
		<h2>Group Stats </h2>
		<table class="stats-table"> 
			<thead>
				<th class="corner sortable">Player</th>
				<th class="sortable">Match Wins</th>
				<th class="sortable">Match Losses </th>
				<th class="sortable"> Win/Loss </th>
				<th class="corner sortable">Tournament Wins </th>
			</thead>
			<% @group_users.each_with_index do |user,i| %>
				<tr>
					<td> <%= user.username %> </td>
					<td> <%= @all_user_wins[i] %> </td>
					<td> <%= @all_user_losses[i]%></td>
					<td> <%= @all_user_win_loss_ratios[i]  %></td> 
					<td> <%= @all_user_tournament_wins[i] %> </td>
				</tr>
			<% end %>
		</table>

		<h3 class="head-to-head-title"> Head to Head</h3>

		<!-- On selection, send AJAX to get the info needed for the table -->
		
		<select class="user-1" onchange="changeEventHandler(event);"> 
			<% @group_users.each do |user| %>
				<option value="<%=user.username%>"> <%=user.username%> </option>
			<% end %>
		</select>
		<p class="vs">VS<p>
		<select class="user-2" onchange="changeEventHandler(event);"> 
			<% @group_users.each do |user| %>
				<option value="<%=user.username%>"> <%=user.username%> </option>
			<% end %>
		</select>

		<table class="head-to-head">
			<thead> 
				<th>Meetings</th>
				<th>Victories</th>
				<th>Defeats</th>
			</thead>
			<tr>
				<td class="meetings">&nbsp</td>
				<td class="victories">&nbsp</td>
				<td class="defeats">&nbsp</td>
			</tr>
		</table>
		
	</section>

<div class="spacer large-1 columns">&nbsp</div>

app/views/groups/showGroupToUser.html.erb
<%= stylesheet_link_tag "groupPageUser" %>
	<div class="spacer custom-size columns">&nbsp</div>
	
	<section class="large-3 columns tournament-listing content">
		<!-- Display old tournaments and their victors -->
		<h3>Completed Tournaments</h3>
		<% if @complete_tournaments.empty? %>
			<p>None</p>
		<% else %>
			<% @complete_tournaments.each_with_index do |t,i| %>
				<ul class="completed-tournament-list"> 
					<li class="tournament-li"> <h5><%= t.name %></h5> <h5> Victor : <%=@champs[i].username%></h5>  <h5>Completed on: <%=t.updated_at.to_s.split(' ')[0]%> </h5></li>
				</ul>
			<% end %>
		<% end %>
	</section>
	
	<section class="large-3 columns tournament-listing content">
		<!-- Link to in progress tournaments -->
		<h3>Active Tournaments</h3>
		<% if @incomplete_tournaments.empty?%>
			<p>None. Get your group's admin to create one!</p>
		<%else%>
			<% @incomplete_tournaments.each do |t| %>
				<ul>
					<li class="tournament-li"> <p><%= link_to t.name, tournament_path(t.id) , method: :GET %></p> </li>
				</ul>
			<% end %>
		<%end%>
	</section>


	<!--       Stats section         -->
	<section class="large-3 columns stats content">
		<h1>Group Stats </h1>
		<table class="stats-table"> 
			<thead>
				<th class="corner sortable">Player</th>
				<th class="sortable">Match Wins</th>
				<th class="sortable">Match Losses </th>
				<th class="sortable"> Win/Loss </th>
				<th class="corner sortable">Tournament Wins </th>
			</thead>
			<% @group_users.each_with_index do |user,i| %>
				<tr>
					<td> <%= user.username %> </td>
					<td> <%= @all_user_wins[i] %> </td>
					<td> <%= @all_user_losses[i]%></td>
					<td> <%= @all_user_win_loss_ratios[i]  %></td> 
					<td> <%= @all_user_tournament_wins[i] %> </td>
				</tr>
			<% end %>
		</table>

		<h3 class="head-to-head-title"> Head to Head</h3>
		<!-- On selection, send AJAX to get the info needed for the table -->
		<input class="group-id" type="hidden" value=<%=@group.id%> >
		<select class="user-1 " onchange="changeEventHandler(event);"> 
			<% @group_users.each do |user| %>
				<option value="<%=user.username%>"> <%=user.username%> </option>
			<% end %>
		</select>
		<p class="vs">VS<p>
		<select class="user-2" onchange="changeEventHandler(event);"> 
			<% @group_users.each do |user| %>
				<option value="<%=user.username%>"> <%=user.username%> </option>
			<% end %>
		</select>

		<table class="head-to-head">
			<thead> 
				<th>Meetings</th>
				<th>Victories</th>
				<th>Defeats</th>
			</thead>
			<tr>
				<td class="meetings">&nbsp</td>
				<td class="victories">&nbsp</td>
				<td class="defeats">&nbsp</td>
			</tr>
		</table>
		
	</section>

<div class="spacer custom-size columns">&nbsp</div>	