config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :except => [:index]
  resources :groups
  resources :memberships
  resources :tournaments do
    resources :matches
  end

  get 'head_to_head/:id', to: 'groups#ajax_head_to_head'

  root to: 'users#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #For adding the ability to log in with username instead of just email
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }#,
  # :format => { } # etc.

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  #Main User Page, shows all their groups
  def show
    @user = current_user
    @user_groups = @user.groups

    @active_groups = []
    @pending_groups = []
    @pending_memberships = []
    @user.memberships.each do |m|
      if (m.status == "active")
        group = Group.find(m.group_id)
        @active_groups.push(group)
      elsif (m.status == "pending")
        group = Group.find(m.group_id)
        @pending_groups.push(group)
        @pending_memberships.push(m)
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= stylesheet_link_tag :application, :media => "all" %>
<%= stylesheet_link_tag "userPage" %>

<div class="large-4 columns content"> 
	<h2>Your Groups</h2>
	<% @active_groups.each do |group| %>
		<ul> 
			<li> <p><%= link_to group.name, group_path(group.id) , method: :GET  %><p> 
			<% if current_user.id == group.admin_id%>
				<button class="delete-group" value=<%=group.id%>>Delete Group</button>
			<% end %>
			</li>
		</ul>
	<% end %>
</div>
<div class="large-4 columns content">
	<h2> Invitations </h2>
	<%if @pending_groups.empty? %>
		<p>No current invites :( Maybe start your own group? </p>
	<% end %>
	<% @pending_groups.each_with_index do |group,i| %>
		<ul class="pending-invites">
		<li> <p><%=group.name%></p>
			 <button class="accept-invite">Accept invite </button> 
			 <input class="group-id" type="hidden" value=<%=group.id%>> 
			 <input class="user-id" type="hidden" value=<%=current_user.id%>>
			 <input class="membership-id" type="hidden" value=<%=@pending_memberships[i].id%>>
		</li>
		</ul>
	<% end %>
</div>
<div class="large-4 columns content">
	<% if flash[:alert] %>
		<p class="error"> <%=flash[:alert]%> </p>
	<% end %>
	<h2>Create a group</h2>
	<label class="group-name">Group Name </label>
	<%= form_tag groups_path, :class => 'create-group', method: :POST do %>
		<input name="group[name]"type="text" >
		<input name="group[admin_id]" type="hidden" value=<%=@user.id%>>
		<button class="create-button"> Create </button>
	<% end %>
</div>